# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Don
email: your-email@domain.com
description: "It's a me!"
baseurl: "/rob" # the subpath of your site, e.g. /blog
url: "http://dawaltconley.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

collections:
    projects:
        output: false

exclude:
    - "about.md"
    - "blog.html"
    - "*/.help.md"

prose:
    rooturl: "_projects"
    media: "media/project-images"
    metadata:
        _projects:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
            - name: "date"
              field:
                  element: "text"
                  label: "Date"
                  value: "CURRENT_DATETIME"
                  placeholder: "YYYY-MM-DD"
            - name: "media"
              field:
                  element: "text"
                  label: "Media"
                  help: >
                      Full url linking to the relevant vimeo or bandcamp page.
            - name: "image"
              field:
                  element: "text"
                  label: "Image"
                  help: >
                      The name and extenson of the image that will appear as the link to the project. You do not need to enter its filepath. You can upload the image while editing this file using the images icon in the toolbar. This will automatically insert a markdown link to the image in the text of your project description. In order for the image to format propperly, you should delete this link and enter the filename here.

# Build settings
markdown: kramdown
