# Global Variables

title: Robert Don
description: "Producer. Mixer. Musician."
baseurl: ""
url: "http://www.robertgdon.com/"
permalink: /:title/
google_analytics:

project_transition_time: 1s

splash_options:
  - name: "original"
    path: "/media/backgrounds/bg-1.jpg"
  - name: "board 1"
    path: "/media/backgrounds/splash-1.jpg"
  - name: "board 2"
    path: "/media/backgrounds/splash-2.jpg"
  - name: "board 2 cropped"
    path: "/media/backgrounds/splash-3.jpg"
  - name: "board 4"
    path: "/media/backgrounds/bg-9.jpg"
  - name: "board 5"
    path: "/media/backgrounds/bg-4-04.jpg"
  - name: "board 6"
    path: "/media/backgrounds/bg-5-01.jpg"
  - name: "board 7"
    path: "/media/backgrounds/bg-7-01.jpg"
  - name: "board 8"
    path: "/media/backgrounds/bg-8.jpg"
  - name: "board 8 b&amp;w"
    path: "/media/backgrounds/bg-8-01.jpg"
  - name: "mic-1"
    path: "/media/backgrounds/mic-1.jpg"
  - name: "mic-2"
    path: "/media/backgrounds/mic-2.jpg"

cta_options:
  - name: "original"
    path: "media/backgrounds/cta-1.jpg"
    position: "center bottom"
  - name: "original cropped"
    path: "/media/backgrounds/splash-3.jpg"
  - name: "board 1"
    path: "media/backgrounds/cta-2.jpg"
    position: "center bottom"
  - name: "board 3"
    path: "/media/backgrounds/bg-1.jpg"
  - name: "board 4"
    path: "/media/backgrounds/bg-9.jpg"
  - name: "board 5"
    path: "/media/backgrounds/bg-4-04.jpg"
  - name: "board 6"
    path: "/media/backgrounds/bg-5-01.jpg"
  - name: "board 7"
    path: "/media/backgrounds/bg-7-01.jpg"
  - name: "board 8"
    path: "/media/backgrounds/bg-8.jpg"
  - name: "board 8 b&amp;w"
    path: "/media/backgrounds/bg-8-01.jpg"
  - name: "mic-1"
    path: "/media/backgrounds/mic-1.jpg"
  - name: "mic-2"
    path: "/media/backgrounds/mic-2.jpg"


# Collections

collections:
  projects:
    output: false

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
  - "node*"
  - "package*.json"
  - "gulpfile.js"

# Prose

prose:
  ignore:
    - "*.html"
    - "*.svg"
    - "*.xml"
    - "*.liquid"
    - "*.js"
    - "*.json"
    - "*.jsonp"
    - "*.rb"
    - "_layouts"
    - "_sass"
    - "_site"
    - "css"
    - "js"
    - "media"
    - "_data/breakpoints.yml"
    - "_data/icon-types.yml"
    - "_data/redirects.yml"
    - "_includes/lorem-ipsum.md"
    - "_config*.yml"
    - "buildspec.yml"
    - "build-failure*"
    - "README.md"
    - ".babelrc"
    - ".nvmrc"
    - ".gitignore"
    - "Gemfile*"
    - "CNAME"
  media: "media/project-images"
  metadata:
    _projects:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
          placeholder: "YYYY-MM-DD"
      - name: "media"
        field:
          element: "select"
          label: "Media Type"
          options:
            - name: "Bandcamp"
              value: "bandcamp"
            - name: "Soundcloud"
              value: "soundcloud"
            - name: "YouTube"
              value: "youtube"
            - name: "Vimeo"
              value: "vimeo"
            - name: "Web Page"
              value: "page"
      - name: "link"
        field:
          element: "text"
          label: "Media Link"
          help: >
            Full url linking to the relevant vimeo or bandcamp page.
          placeholder: "http://www.example.com/page"
      - name: "tralbum_id"
        field:
          element: "text"
          label: "Tralbum ID"
          help: >
            Bandcamp only. A number associated with the linked track or album.
          placeholder: "0123456789"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: >
            The name and extenson of the image that will appear as the link to the project. You do not need to enter its filepath. You can upload the image while editing this file using the images icon in the toolbar. This will automatically insert a markdown link to the image in the text of your project description. In order for the image to format propperly, you should delete this link and enter the filename here.
